### ISSUE TITLE
Randomly not working in cutscenes since 6.5

### ISSUE THREAD

**Issue by AikoTM** [chirpxiv/PalettePlus#20]
It works fine outside of cutscenes and even during some of them.
But for example, during the cutscenes of the new Alliance Raid it occasionally doesn't work.

// Also doesn't seem to apply when you apply a design via glamourer. I should probably say that I have a palette applied via persistence tab. -- Restarting glamourer seems to have fixed that. For now?

**Comment by fallingstar275** [comment]
I have been having this problem as well, unfortunately. Any scripted cutscene, it seems to not work since the update. I checked out The Unending Journey and it seems like in all those cutscenes, Palette+ isn't working either, when I swear it was working before :( I have the persistence set to her no matter what as well. Hoping a solution can be found, because I have no idea what I can do to fix it :(

**Comment by Zylph** [comment]
I have this problem in MSQ Cutscenes as well. I opened the Palette options mid cutscene. It does not see my character in the Edit Players list. Only the NPCs.  Perhaps this has something to do with it?

**Comment by chirpxiv** [comment]
This should be addressed in the latest release. Please let me know if you're still having issues.

**Comment by orenji** [comment]
Palette Plus is not being applied in my cutscenes still as of today :(

**Comment by AikoTM** [comment]
> This should be addressed in the latest release. Please let me know if you're still having issues.

So far, it seems to work for me.
I checked some cutscenes in the inn room before the update to make sure they are "bugged" and then after the update where everything worked fine.

**Comment by orenji** [comment]
Wasn't working for me and realized I had the update and it works now! :)
